spring.application.name=UrbanInn
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/urban_inn?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Rushikesh@18
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.time-zone=UTC

app.jwt.secret=5A7134743777217A24432646294A404E635266546A576E5A7234753778214125
app.jwt.expiration-ms=86400000
app.jwt.guest-expiration-ms=43200000


logging.level.com.rushikesh=DEBUG
logging.level.org.springframework.security=INFO